[workspace]
resolver = "3"
members = ["mnist_infer","mnist_ml", "text_classification_infer", "text_classification_news", "text_gen_train"]

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[workspace.metadata.bacon]
analyzer = "standard"

[workspace.dependencies]
